main: com.craftilandia.mobspawners.Main
name: Mob_Spawners
version: 2.0
author: raton023
website: http://dev.bukkit.org/bukkit-plugins/mobs-spawners/
commands:
    getspawner:
        usage: /getspawner <mob>
        description: get the spawn of a mob type.
permissions:
    mobspawners.getdrop:
        description: permission to get the spawner when breaking a spawner.
        default: true
    mobspawners.getspawner:
        description: permission to use /getspawner command.
        default: op
